[program:mi_api]
command=/home/eriikmp/mi_api/venv/bin/python /home/eriikmp/mi_api/api.py
directory=/home/eriikmp/mi_api
user=eriikmp
autostart=true
autorestart=true
stderr_logfile=/var/log/mi_api.err.log
stdout_logfile=/var/log/mi_api.out.log
